version: 1.2
workflows:
   - subclass: CWL
     name: a> out.txt && cat 'hello' > hack.txt &&; 
     primaryDescriptorPath: /potato.cwl
     authors:
       - name: UCSC Genomics Institute
         role: Institute
         affiliation: UCSC
     publish: True
     testParameterFiles:
         - /test/dockstore.cwl.json

