version: 1.2
workflows:
   - subclass: CWL
     name: 222test222
     primaryDescriptorPath: /potato.cwl
     authors:
       - name: UCSC Genomics Institute
         role: Institute
         affiliation: UCSC
     publish: True
     testParameterFiles:
         - /test/dockstore.cwl.json
!!java.util.Date
date: 25
month: 12
year: 2016
